services:
  - type: web
    name: springboot-backend
    env: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
